### ISSUE TITLE
The Warmth of Home prophecy progression is hard to read

### ISSUE THREAD

**Issue by Fly0DB** [AlexKage69/OlympusExtra#106]
![Image 226](https://user-images.githubusercontent.com/73316992/194702692-f46acb5f-1674-4c19-9f9d-dfcf43ee7761.png)

**Comment by AlexKage69** [comment]
Which language do you use? And I'll double check if it does it in english.

**Comment by Fly0DB** [comment]
Russian. Switched to english, same issue here.

**Comment by Sarai91** [comment]
I can confirm this is exactly what it looks like in English.

**Comment by AlexKage69** [comment]
Fix in the next release.
