### ISSUE TITLE
Reproduceable Crash on Hestia/Dionysus Trial (forgiven)

### ISSUE THREAD

**Issue by Sarai91** [AlexKage69/OlympusExtra#109]
Load the attached save. Select Hestia first, then Dio, who forgives you. The game crashes immediately upon opening Dio's boons. I can include my mod folder as well, but it's 2.7GB.

System: Steam Deck (linux)

Mods:
Olympus Extra
Pony Aspect Extender
Pony Aspect Fusion
Ello's Reroll Everything
Hades Room Secret Indicator
Lower Keepsake Threshold
More Pom Options
Pony QOL (only chamber count, commendations, GodKeepsakes, AlwaysEncounterStoryRooms, PoolOfPurging)
Ramping Fish Chance
Resources Scale with Heat (all options set to 4, no change to % increase)
Simplified Mirror of the Night Expanded
Simply Better Wretched Broker

Save and log: [link](https://drive.google.com/file/d/1szlvnRgAUeg3eCzCl2k6ljprf9rhowWu/view?usp=sharing)

**Comment by Sarai91** [comment]
No crash if you select Dio then Hestia, but you also aren't forgiven.

**Comment by AlexKage69** [comment]
These are hard to reproduce. If you ever encounter that bug make a copy of you save file and send it to us. We'll be able to reproduce and check what happen with Hestia.

**Comment by Sarai91** [comment]
Fortunately I do have a copy of the save file, I just got your share request for the Drive file.

**Comment by BillVGN** [comment]
Crash happened with Hestia and Artemis, picked Hestia, Artemis forgave me than crashed. After I've sent SuperGiant crash report, game continued but didn't show any boons inside frame to pick one. I had to give my run up 'cause I was stuck,

**Comment by phypoh** [comment]
@BillVGN Can i check if you were running with Hermes's Plume when the crash occured

**Comment by AlexKage69** [comment]
This should be fixed
