### ISSUE TITLE
Apollo Trials are too difficult 

### ISSUE THREAD

**Issue by Sarai91** [AlexKage69/OlympusExtra#110]
If you get a god Trial with Apollo and don't select him, it's exceedingly difficult to kill the last mob in a wave. Especially in melee, if you can't deal more than 500 damage in a hit, the last mob is healed for 500 every 2 seconds or so and the fight can last ages. If you aren't able to consistently stay out of the blinding zone or knock the mob out so it can't heal, you're SOL.

**Comment by AlexKage69** [comment]
Noted. I'll try to add a AI that detect if there only one enemy left then target Zagreus instead of the last enemy. That might help with that issue

**Comment by Sarai91** [comment]
If you're in melee distance that doesn't really solve the issue, but reducing the frequency when there's one left would probably work well.

**Comment by AlexKage69** [comment]
As proposed, when 1 enemy is remaining against Apollo, Attacks goes from 2 sec to 5 sec to let the time to kill that enemy. Fix in next release.

**Comment by phypoh** [comment]
Fixed with new Hestia release
