### ISSUE TITLE
Pressure Points is not in the list of prerequisites for Striking Sparks

### ISSUE THREAD

**Issue by Fly0DB** [AlexKage69/OlympusExtra#118]
Got Striking Sparks with only Pressure Points as Artemis boons.
![Screenshot_20221112_221047](https://user-images.githubusercontent.com/73316992/201488827-1bac32e9-6e13-4c9e-9f0d-792689bd0951.png)

**Comment by AlexKage69** [comment]
Now it does, Striking Sparks Artemis Requirement are now: Deadly Strike, Deadly Flourish, True Shot and Pressure Points.
