### ISSUE TITLE
Empty message from Apollo

### ISSUE THREAD

**Issue by Fly0DB** [AlexKage69/OlympusExtra#119]
Started a run with Apollo's keepsake and received a textless message from him. From what I've heard it should be ApolloMiscPickup11.
![Screenshot_20221119_163421](https://user-images.githubusercontent.com/73316992/202851300-f05d50db-bed2-4f0c-80e2-69734dd6d79b.png)

**Comment by AlexKage69** [comment]
Text displayed should be now: {#DialogueItalicFormat}Hey, look here, Zagzag,\nMade a haiku just for you,\nGood luck escaping.{#PreviousFormat}.
