### ISSUE TITLE
Fated List: Mercy and Forgiveness

### ISSUE THREAD

**Issue by BillVGN** [AlexKage69/OlympusExtra#148]
First and foremost: thanks a lot for this mod/dlc ! I don't know how you guys were able to implement such exquisite and sensational artwork as well as Supergiant developers did. Am I so bold to ask if you did some jobs or were employed by them? None of this matters actually because you guys are pros yourselves.

Now, I have an issue... I don't really know if it is or if it's just me lacking something, but I am unable to advance the Mercy and Forgiveness fated list quest any further than Zeus and Poseidon. I already picked Hestia instead of Dionysus and Aphrodite but they seem reeeealy pissed off, nowhere near merciful or forgiving towards me!

Am I doing this the wrong way or is this just a bug? HELP ME!

Thanks again for this great work. 

Peace out!

**Comment by AlexKage69** [comment]
Thanks! No, we never worked for SGG. We wish ;)

Each time, you pick hestia instead of someone, you have a 20% chance to activate the forgiveness. This is to make the forgiveness mechanic last longer on new game. Because you would just speed through it or think hestia always forgives. Keep playing, and you'll get them all. 

Spoiler: one of the god doesn't fogive hestia.

**Comment by BillVGN** [comment]
> Thanks! No, we never worked for SGG. We wish ;)
> 
> Each time, you pick hestia instead of someone, you have a 20% chance to activate the forgiveness. This is to make the forgiveness mechanic last longer on new game. Because you would just speed through it or think hestia always forgives. Keep playing, and you'll get them all.
> 
> Spoiler: one of the god doesn't fogive hestia.

You guys did all this on your own?? Wow, that's talent right there!

Thanks for the quick answer. Now I'll sure play a "few" more times to fulfill this quest.

PSS: One god who won't forgive you when picking Hestia first? Hmm, I think only of goddesses like Demeter or Aphrodite.. did you say "god" to mislead me? hahaha

**Comment by AlexKage69** [comment]
Since this is not a bug, I'll close the ticket, but consider joining Hades Modding Discord. It's full of nice stuff about Hades!
