### ISSUE TITLE
Incorrect audio files playing

### ISSUE THREAD

**Issue by Spedwards** [AlexKage69/OlympusExtra#166]
Just upgraded from v1.2.1 to v1.2.3. (I used `git pull` since the release is from the latest commit anyway, and overwrote the VO.fsb file).

When purchasing items from the House Contractor, random voice lines are played. I've heard Artemis, Demeter, and Zagreus speaking to Sisyphus; you get the point.

All audio was all fine on v.1.2.1.

Here's a YouTube video of this happening: https://www.youtube.com/watch?v=dk4fFTSH6A0

For what it's worth, this seems to apply to every audio line. Not just House Contractor lines.

**Comment by AlexKage69** [comment]
@Spedwards did you also update the vo.fsb in mod/olympusextra/audio? You can also get the fully done version on nexus.

**Comment by Spedwards** [comment]
> @Spedwards did you also update the vo.fsb in mod/olympusextra/audio? You can also get the fully done version on nexus.

>  and overwrote the VO.fsb file

Yes.

**Comment by AlexKage69** [comment]
Can you confirm that both vo.fsb in mod/olympusextra/audio and audio/FMOD/.../Vo.fsb are 695 kb? It would confirm that the issue is not the vo.fsb but the vo.h.

**Comment by Spedwards** [comment]
> Can you confirm that both vo.fsb in mod/olympusextra/audio and audio/FMOD/.../Vo.fsb are 695 kb? It would confirm that the issue is not the vo.fsb but the vo.h.

I grabbed the VO.fsb file from the [v1.2.3 release on GitHub](https://github.com/AlexKage69/OlympusExtra/releases/tag/v1.2.3) which is 695 MB.

The VO.fsb file within `audio/FMOD/.../` is 711 MB though which matches the size of the VO.fsb file available from NexusMods.

physiX helped me getting this working on Discord.
