### ISSUE TITLE
Typos in Codex Text

### ISSUE THREAD

**Issue by szarrougtw** [AlexKage69/OlympusExtra#167]
https://github.com/AlexKage69/OlympusExtra/blob/0a528df008cb2b0310d959ca73ca4254bfd99bbb/Apollo/Text/en/CodexText.en.sjson#L11
https://github.com/AlexKage69/OlympusExtra/blob/0a528df008cb2b0310d959ca73ca4254bfd99bbb/Apollo/Text/en/CodexText.en.sjson#L16
https://github.com/AlexKage69/OlympusExtra/blob/0a528df008cb2b0310d959ca73ca4254bfd99bbb/Apollo/Text/en/CodexText.en.sjson#L21

I believe prohecy here should be prophecy

**Comment by phypoh** [comment]
Typo has been fixed, and will be patched in the upcoming Hera update, thanks for the feedback!
