### ISSUE TITLE
v1.3.1 can't run at all

### ISSUE THREAD

**Issue by Allegrett** [AlexKage69/OlympusExtra#175]
![20230902093753](https://github.com/AlexKage69/OlympusExtra/assets/39668515/3550b595-cf77-49d1-95d9-7fe6c26d446c)
The newest realease can't run well at all... However when I reload the v.1.2.3 everything is all right.

**Comment by AlexKage69** [comment]
Were you able to run 1.3.0 from nexus? Because 1.3.1 is working on my end. Wht does the modimporter.exe say?

**Comment by Allegrett** [comment]
The modimporter.exe reports no error，and I didn't run 1.3.0 . I am more interested in programming , just a  tyro.

**Comment by AlexKage69** [comment]
Like i said it run on my end. Did you take it from github or nexus? If it was a typo in the code modimporter would fail on one of the file.

**Comment by AlexKage69** [comment]
V1.3.1 works for me, i downloaded it fresh and don't get any error.

**Comment by Allegrett** [comment]
Ops. I mean I'm a Novice of programming and maybe English. I take it from github.

**Comment by AlexKage69** [comment]
Did you add the Vo.fsb in audio/? Might be missing and when running modimporter.exe it would tell you its missing. Worst case you can take it from nexus since the vo.fsb is already in the right place.

**Comment by Allegrett** [comment]
Yes, the Vo.fsb is audio. 
1.3 just doesn't work . 1.2 is all right for me

**Comment by AlexKage69** [comment]
@phypoh will try 1.3.1 and we'llhave more info on why it doesn't work. You can also ask Hades Modding Discord.

**Comment by phypoh** [comment]
1.3.1 on GitHub works for me too, maybe it's the modimporter/ModUtil version?

**Comment by Allegrett** [comment]
Clever Lady phypoh is right ! The key issue is the ModUtil version !

**Comment by phypoh** [comment]
Solved :)
