### ISSUE TITLE
Event:DemeterWithHera01 ans HeraAboutOlympianReunionQuest01

### ISSUE THREAD

**Issue by Allegrett** [AlexKage69/OlympusExtra#187]
Hera‘s dialogue may should cue to Hera_0058

Amd HeraReunionQuest is cued to a duplicate ID which is cued to Event: DionysusWithHera01

**Comment by AlexKage69** [comment]
Thanks for the checkups. I changed them, but I'll review them once the Hera's recording comes in. Should be coming in sometimes in February. ;)
