### ISSUE TITLE
Hera's Queen's Gambit: Missing text on anvil

### ISSUE THREAD

**Issue by threethan** [AlexKage69/OlympusExtra#190]
A string seems to be missing for Queen's Gambit when viewing the anvil offered by Charon in the temple of styx. See attached screenshot:
![image](https://github.com/AlexKage69/OlympusExtra/assets/12588584/ff01bbb6-8c1e-4e5f-a6e5-6ad41b524324)

**Comment by AlexKage69** [comment]
Thanks i'll look at it

**Comment by AlexKage69** [comment]
This will be in 1.3.4. Thanks for your help.
![Hades 2024-01-25 8_47_57 AM](https://github.com/AlexKage69/OlympusExtra/assets/44212358/d3ea9a04-52b9-4692-aea7-9ef6bfa152b0)
