### ISSUE TITLE
Hera has no voice

### ISSUE THREAD

**Issue by Mocha1958** [AlexKage69/OlympusExtra#191]
The game runs fine and all characters sound normal, including Apollo
But Hera is mute
I made sure the file I downloaded was the latest, and VO.fsb in the right place
How can i slove it

**Comment by AlexKage69** [comment]
It's not released yet. We have done the recording, but we need to edit them. They should be part of 1.3.4. Stay tune.

**Comment by Mocha1958** [comment]
> 它还没有发布。我们已经完成了录制，但我们需要对其进行编辑。它们应该是 1.3.4 的一部分。请保持关注。

ok thanks all your work and VAs
