### ISSUE TITLE
ApolloShout damage

### ISSUE THREAD

**Issue by phypoh** [AlexKage69/OlympusExtra#50]
We need to balance the numbers for this one. Low priority since it's already working, but it would be good to get some feedback from players as well

**Comment by AlexKage69** [comment]
Damage shout be fine. Since Zagreus is invulnerable, it makes the shout very strong. Lower damage is fine and there's Pom to improve it, but the base damage is fine like it is. All Shout needs would be better mechanics.

**Comment by phypoh** [comment]
Noted. I'll keep an eye on the numbers, but I'll still keep this open for now

**Comment by AlexKage69** [comment]
Added that only the first Laser does 100% damage so 15dmg. Other will do 15% each. That's way better.
