### ISSUE TITLE
Mirage Shot with Blinding Bomb gives extra casts

### ISSUE THREAD

**Issue by virtualn3uron** [AlexKage69/OlympusExtra#57]
I noticed that once I lob multiple casts across a room,after the fog wears off let's me pick up both a regular cast and the mirage shot duplicate as a regular cast.
![Apollo bug](https://user-images.githubusercontent.com/106459179/170850529-14639454-81d6-44dc-9f68-1cf66d39c1e4.png)

**Comment by virtualn3uron** [comment]
I can also individually pick one of those up and lob it again, applying mirage shot and getting another cast out of it

**Comment by AlexKage69** [comment]
Did you fix that?

**Comment by phypoh** [comment]
Fixed on OE-Apollo, by Alex
