### ISSUE TITLE
Melting Heart and Homecoming don't have a fated choice icon

### ISSUE THREAD

**Issue by Fly0DB** [AlexKage69/OlympusExtra#98]
Melting Heart and Homecoming are in the list of prophecies, but in the codex and when choosing a boon, they do not have a fated choice icon. However, if you select them, then in the list of prophecies they will be counted as selected.

**Comment by AlexKage69** [comment]
Good catch! It seems like Deathless Stand and Last Stand are not part of the Fated List too since they are consummable in the code and not regular trait. The same happens with Melting Hearth, Homecoming and Perseverance. @Fly0DB Do you think we should remove them from the prophecies like SGG did?

**Comment by Fly0DB** [comment]
I would prefer all 3 gifts to be included in the prophecy. But if it's hard to do, it's okay to remove them.

**Comment by AlexKage69** [comment]
We removed Future Sight, Golden Fleece for Apollo and Melting Heart, Temperance and Homecoming for Hestia from the fated list. To be consistent with other gods fated list.
